
HelloContent = record {
    id: i32;
    text: string;
    authors: set<string>;
}

HelloMessage = record {
    id: i32;
    tag: string;
    contents: list<HelloContent>;
    data: binary;
}

HelloWorld = interface +c {
    static create(msg: string, callback: HelloCallback): HelloWorld;
    msg(): HelloMessage;
}

HelloCallback = interface +j {
    invoke(msg: HelloMessage);
}
